version = 1

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Stephan Druskat <stephan.druskat@dlr.de>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["*.ipynb"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Stephan Druskat <stephan.druskat@dlr.de>"
SPDX-License-Identifier = "MIT"

